Dev to main (demo inside readme)
stepancar-web-programming/2023-fall-lab-portfolio-petrenko-a.-a pull request #5
Opened 2024-01-19 09:56 UTC by Deadshotop

2024-01-20 03:21 UTC, stepancar commented on img/image1.jpg
<img width="666" alt="Screenshot 2024-01-19 at 7 21 15 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-petrenko-a.-a/assets/2854910/72cdfc9e-a3d4-499b-b4ed-0039e21321f1">
Фотография отображается некорректно

2024-01-20 03:25 UTC, stepancar commented on script.js
> +let currentIndex = 0;
Обратите внимание на то , что состояние вашей програмы доступно из вне, сторонний скрипт может влиять на сохраненное состояние

2024-01-20 03:28 UTC, stepancar commented on script.js
> +setInterval(nextSlide, 3000);
Давайте представим ситуацию, вам нужно удалить слайдер со страницы чтобы показать что-то другое. 
В вашем случае приложение не является SPA поэтому такой потребности нет, но давайте подумаем, как написать код так, чтобы можно было удалить элемент, а таймер не работал впустую

2024-01-20 04:47 UTC, stepancar commented
На защиту ожидаю внедрение автоматизации линтеры и подключение матрик яндекс/ гугл/микспанел на выбор. Трекеры должны собирать статистику  перехода на страницы, нажатия на кнопки карусели картинок

2024-01-21 17:24 UTC, Deadshotop commented on script.js
> +setInterval(nextSlide, 3000);
Можно сделать функцию stopSlider, которая будет вызываться перед удалением слайдера, и она будет останавливать таймер

function stopSlider() {
  clearInterval(sliderInterval);
}

2024-01-21 22:02 UTC, stepancar commented on script.js
> +setInterval(nextSlide, 3000);
Давайте сделаем

2024-01-23 11:13 UTC, Deadshotop commented on img/image1.jpg
Исправил. (см демо)

2024-01-23 11:13 UTC, Deadshotop commented on script.js
> +let currentIndex = 0;
Поместил код, связанный со слайдером внутрь модуля sliderModule, который  содержит в себе все функции и данные, необходимые для работы со слайдером

2024-01-23 11:14 UTC, Deadshotop commented on script.js
> +setInterval(nextSlide, 3000);
Теперь у слайдера есть функция workAutoSlide, которая обеспечивает работу с таймером и автопереключением слайдов. Также появилась кнопка workAutoSlide, которая работает таким образом, что по дефолту автопереключение есть и работает. При нажатии на эту кнопку, автопереключение перестает работать, а текст внутри кнопки меняется на "возобновить автослайд", при повторном нажатии на кнопку, автослайд снова включается.

2024-01-24 04:48 UTC, stepancar requested changes
<img width="1716" alt="Screenshot 2024-01-23 at 8 47 58 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-petrenko-a.-a/assets/2854910/23b415ae-614a-4a58-9566-708ad4c5ce2f">

2024-01-24 04:51 UTC, stepancar requested changes
Футер не всегда прижат к низу страницы
<img width="451" alt="Screenshot 2024-01-23 at 8 50 49 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-petrenko-a.-a/assets/2854910/338e6639-24a7-49bc-9328-0fbdb2dea087">

2024-01-24 05:02 UTC, stepancar requested changes
Логика слайдера такова, что переключение слайда по кнопке не сбрасывает анимацию, в итоге получается такой эффект, что ты нажимаешь, анимация стартует, а через 100ms срабатывает автоматическое перелистывание.

2024-01-24 05:05 UTC, stepancar requested changes
Работа не выглядит законченной.
На узких экранах нет отступов слева справа, при этому у галереи они есть.
<img width="783" alt="Screenshot 2024-01-23 at 9 03 01 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-petrenko-a.-a/assets/2854910/49333d97-637d-408f-94d8-26ded72fe688">

Видео занимает max 50% даже на маленьких экранах.

2024-01-26 04:52 UTC, stepancar approved these changes

2024-01-26 04:53 UTC, merged